# Generated by Django 6.1 on 2026-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
